spring:
  profiles:
    active:
      - dev
---
server:
  port: 8881
spring:
  profiles: dev
  application:
    name: familybusi-config-client
  cloud:
    #配置注册中心
    zookeeper:
      connect-string: 172.18.232.196:2281,172.18.232.197:2281,172.18.232.198:2281
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
---
server:
  port: 8882
spring:
  profiles: test
  application:
    name: familybusi-config-client
  cloud:
    #配置注册中心
    zookeeper:
      connect-string: 172.18.232.196:2281,172.18.232.197:2281,172.18.232.198:2281
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true