spring:
  profiles:
    active:
      - dev
---
server:
  port: 8881
spring:
  profiles: dev
  application:
    name: familybusi-config-client
  cloud:
    #配置注册中心
    zookeeper:
      connect-string: 172.16.46.130:2181,172.16.46.131:2181,172.16.46.132:2181
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
---
server:
  port: 8882
spring:
  profiles: test
  application:
    name: familybusi-config-client
  cloud:
    #配置注册中心
    zookeeper:
      connect-string: 172.16.46.130:2181,172.16.46.131:2181,172.16.46.132:2181
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
